BINANCE_API_KEY=YOUR_API_KEY_HERE
BINANCE_API_SECRET=YOUR_API_SECRET_HERE
LEVERAGE=50

# Squeeze Momentum Parameters
SQUEEZE_TIMEFRAME=570
BB_LENGTH=570
KC_LENGTH=570
BB_MULT=0.8
KC_MULT=0.6
USE_TRUE_RANGE=True

# ADX Parameters
ADX_PERIODS=570
ADX_THRESHOLD=25

# Daily PNL Limits
DAILY_PROFIT_TARGET=1000.0
DAILY_LOSS_LIMIT=-100.0
